/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.exceptions.IllegalOrphanException;
import controlador.exceptions.NonexistentEntityException;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Equipaje;
import modelo.Pasajero;
import modelo.Reserva;
import modelo.ReservaPK;
import static vista.PrincipalFrame.PrincipalPanel;
import static vista.PrincipalFrame.equipajeJpaController;
import static vista.PrincipalFrame.pasajeroJpaController;
import static vista.PrincipalFrame.reproducirS;
import static vista.PrincipalFrame.reservaJpaController;

/**
 *
 * @author Nicolas Ospitia
 */
public class EliminarPasajeroPanel extends javax.swing.JPanel {

    private Image imagen;
    private Pasajero pasajero;
    protected List <Reserva> reservas = reservaJpaController.findReservaEntities();
    protected List <Pasajero> pasajeros = pasajeroJpaController.findPasajeroEntities();
    /**
     * Creates new form EliminarPasajeroPanel
     */
    public EliminarPasajeroPanel() {
        initComponents();
        reservasL.setVisible(false);
        jScrollPane1.setVisible(false);
        EliminarB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pasajeroCedulaL = new javax.swing.JLabel();
        idreservaL = new javax.swing.JLabel();
        tipoDePagoL = new javax.swing.JLabel();
        reservasL = new javax.swing.JLabel();
        idpasajeroT = new javax.swing.JTextField();
        BuscarB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EliminarB = new javax.swing.JButton();
        NombreT = new javax.swing.JLabel();
        tipoDocumentoT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservasList = new javax.swing.JTextArea();
        AtrasB = new javax.swing.JButton();

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));

        pasajeroCedulaL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        pasajeroCedulaL.setText("Nombre");

        idreservaL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        idreservaL.setText("ID pasajero");

        tipoDePagoL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        tipoDePagoL.setText("Tipo de documento");

        reservasL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        reservasL.setText("Reservas");

        idpasajeroT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        idpasajeroT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BuscarB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        BuscarB.setText("Buscar");
        BuscarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar pasajero");

        EliminarB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        EliminarB.setText("Eliminar");
        EliminarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBActionPerformed(evt);
            }
        });

        NombreT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        tipoDocumentoT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        reservasList.setColumns(15);
        reservasList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        reservasList.setRows(5);
        reservasList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(reservasList);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idreservaL)
                            .addComponent(pasajeroCedulaL)
                            .addComponent(tipoDePagoL)
                            .addComponent(reservasL))
                        .addGap(34, 34, 34)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreT)
                            .addComponent(tipoDocumentoT)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idpasajeroT, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(BuscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(EliminarB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idreservaL)
                            .addComponent(idpasajeroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(pasajeroCedulaL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NombreT))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDePagoL)
                    .addComponent(tipoDocumentoT))
                .addGap(22, 22, 22)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservasL)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(EliminarB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AtrasB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/Atras.png"))); // NOI18N
        AtrasB.setContentAreaFilled(false);
        AtrasB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/Atras_G.png"))); // NOI18N
        AtrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtrasB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtrasB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBActionPerformed
        // TODO add your handling code here:
        boolean found = false;
        String reservas = "";
        for(Pasajero p : pasajeros){
            if(p.getCedula().toString().equals(idpasajeroT.getText())){
                NombreT.setText(p.getNombre());
                tipoDocumentoT.setText(p.getTipoDeDocumento());
                found = true;
                if(p.getReservaCollection() != null){
                    reservasL.setVisible(true);
                    jScrollPane1.setVisible(true);
                    for(Reserva r : p.getReservaCollection()){
                        reservas += r.getReservaPK().getIdreserva() + "\n";
                    }
                    reservasList.setText(reservas);
                }
                pasajero = new Pasajero(Long.parseLong(idpasajeroT.getText()), p.getNombre(), p.getTipoDeDocumento());
                if(p.getReservaCollection() != null) pasajero.setReservaCollection(p.getReservaCollection());
                reproducirS("bonkS.mp3");
                EliminarB.setVisible(true);
                break;
            }
        }
        if(found == false){
            this.Clean();
            reproducirS("errorS.mp3");
            JOptionPane.showMessageDialog(this, "No se ha encontrado al pasajero");
        }
    }//GEN-LAST:event_BuscarBActionPerformed

    private void EliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBActionPerformed
        try {
            // TODO add your handling code here:
            
            if(pasajero.getReservaCollection() != null) eliminarReservas(pasajero);
            pasajeroJpaController.destroy(Long.parseLong(idpasajeroT.getText()));
            JOptionPane.showMessageDialog(this, "Se ha eliminado la reserva con éxito");
            EliminarPasajeroPanel EliminarP = new EliminarPasajeroPanel();
            PrincipalPanel.setVisible(false);
            PrincipalPanel.removeAll();
            PrincipalPanel.add(EliminarP);
            PrincipalPanel.setVisible(true);
            this.setBounds(500, 100, 780, 700);
            reproducirS("bonkS.mp3");
            System.gc();
        } catch (IllegalOrphanException ex) {
            Logger.getLogger(EliminarReservaPanel.class.getName()).log(Level.SEVERE, null, ex);
            reproducirS("errorS.mp3");
            JOptionPane.showMessageDialog(this, "Se ha producido un error: " + ex);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(EliminarReservaPanel.class.getName()).log(Level.SEVERE, null, ex);
            reproducirS("errorS.mp3");
            JOptionPane.showMessageDialog(this, "La reserva que desea eliminar no existe.");
        }
    }//GEN-LAST:event_EliminarBActionPerformed

    private void AtrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBActionPerformed
        // TODO add your handling code here:
        PasajeroPanel PasajeroP = new PasajeroPanel();
        PrincipalPanel.setVisible(false);
        PrincipalPanel.removeAll();
        PrincipalPanel.add(PasajeroP);
        PrincipalPanel.setVisible(true);
        this.setBounds(500, 100, 780, 700);
        reproducirS("backS.mp3");
        System.gc();
    }//GEN-LAST:event_AtrasBActionPerformed

    public void eliminarReservas(Pasajero pasajero) {
        for (Reserva reserva : pasajero.getReservaCollection()) {
            if(reserva.getEquipajeCollection() != null) eliminarEquipaje(reserva);
            try {
                reservaJpaController.destroy(reserva.getReservaPK());
            } catch (IllegalOrphanException ex) {
                Logger.getLogger(EliminarPasajeroPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(EliminarPasajeroPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    public void eliminarEquipaje(Reserva reserva){
        for(Equipaje equipaje : reserva.getEquipajeCollection()){
            try {
                equipajeJpaController.destroy(equipaje.getEquipajePK());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(EliminarReservaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void Clean(){
        idpasajeroT.setText("");
        NombreT.setText("");
        tipoDocumentoT.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasB;
    private javax.swing.JButton BuscarB;
    private javax.swing.JButton EliminarB;
    private javax.swing.JLabel NombreT;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField idpasajeroT;
    private javax.swing.JLabel idreservaL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pasajeroCedulaL;
    private javax.swing.JLabel reservasL;
    private javax.swing.JTextArea reservasList;
    private javax.swing.JLabel tipoDePagoL;
    private javax.swing.JLabel tipoDocumentoT;
    // End of variables declaration//GEN-END:variables
}
