/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RutasJpaController;
import java.awt.Graphics;
import java.awt.Image;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import modelo.Rutas;
import static vista.PrincipalFrame.PrincipalPanel;

/**
 *
 * @author Nicolas Ospitia
 */
public class RutasPanel extends javax.swing.JPanel {

    private Rutas ruta;
    private RutasJpaController rutaControlador;
    private EntityManagerFactory emf;
    private Image imagen;
    /**
     * Creates new form RutasPanel
     */
    public RutasPanel() {
        initComponents();
        ruta = new Rutas();
        emf = Persistence.createEntityManagerFactory("ReservaBusPU");
        rutaControlador = new RutasJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloRuta = new javax.swing.JLabel();
        CrearRuta = new javax.swing.JButton();
        ConsultarRuta = new javax.swing.JButton();
        EditarRuta = new javax.swing.JButton();
        EliminarRuta = new javax.swing.JButton();
        AtrasRuta = new javax.swing.JButton();

        TituloRuta.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        TituloRuta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/Trutas.png"))); // NOI18N

        CrearRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        CrearRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/RutasIcon.png"))); // NOI18N
        CrearRuta.setText("Crear ruta");
        CrearRuta.setAlignmentX(100.0F);
        CrearRuta.setAlignmentY(100.0F);
        CrearRuta.setContentAreaFilled(false);
        CrearRuta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CrearRuta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/RutasIcon_G.png"))); // NOI18N
        CrearRuta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CrearRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRutaActionPerformed(evt);
            }
        });

        ConsultarRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        ConsultarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ConsultarIcon.png"))); // NOI18N
        ConsultarRuta.setText("Consultar");
        ConsultarRuta.setContentAreaFilled(false);
        ConsultarRuta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConsultarRuta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ConsultarIcon_G_G.png"))); // NOI18N
        ConsultarRuta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ConsultarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarRutaActionPerformed(evt);
            }
        });

        EditarRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        EditarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ConsultarIcon.png"))); // NOI18N
        EditarRuta.setText("Editar ruta");
        EditarRuta.setContentAreaFilled(false);
        EditarRuta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarRuta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ConsultarIcon_G_G.png"))); // NOI18N
        EditarRuta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarRutaActionPerformed(evt);
            }
        });

        EliminarRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        EliminarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/EliminarIcon.png"))); // NOI18N
        EliminarRuta.setText("Eliminar ruta");
        EliminarRuta.setContentAreaFilled(false);
        EliminarRuta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarRuta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/EliminarIcon_G_G.png"))); // NOI18N
        EliminarRuta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRutaActionPerformed(evt);
            }
        });

        AtrasRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/Atras.png"))); // NOI18N
        AtrasRuta.setContentAreaFilled(false);
        AtrasRuta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/Atras_G.png"))); // NOI18N
        AtrasRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtrasRuta)
                .addGap(160, 160, 160)
                .addComponent(TituloRuta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AtrasRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloRuta))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearRutaActionPerformed

    private void ConsultarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarRutaActionPerformed

    private void EditarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarRutaActionPerformed

    private void EliminarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarRutaActionPerformed

    private void AtrasRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasRutaActionPerformed
        // TODO add your handling code here:
        MenuPrincipal Menu = new MenuPrincipal();
        PrincipalPanel.setVisible(false);
        PrincipalPanel.removeAll();
        PrincipalPanel.add(Menu);
        PrincipalPanel.setVisible(true);
        this.setBounds(500,100,780, 700);
    }//GEN-LAST:event_AtrasRutaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasRuta;
    private javax.swing.JButton ConsultarRuta;
    private javax.swing.JButton CrearRuta;
    private javax.swing.JButton EditarRuta;
    private javax.swing.JButton EliminarRuta;
    private javax.swing.JLabel TituloRuta;
    // End of variables declaration//GEN-END:variables
    @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("./Imagenes/Fondogeneral.png")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
}
